[workspace]
members = [
    "anchor/programs/bounty_escrow",
    "anchor/programs/vulnerability_registry",
    "anchor/programs/reputation_nft"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
bounty_escrow = "3aiStNroDenw7KpSKXvFWVFox35gCk4FcUx8nzXRF2HH"
vulnerability_registry = "5mCoaixH9VVepuSsnhB769263Gg4RqBCEkkoJuHaH69K"
reputation_nft = "HsxZ1cg5H1zvvdyngaLTrB9DZ1YFrEAFMNR21fKCzioW"

[programs.devnet]
bounty_escrow = "3aiStNroDenw7KpSKXvFWVFox35gCk4FcUx8nzXRF2HH"
vulnerability_registry = "5mCoaixH9VVepuSsnhB769263Gg4RqBCEkkoJuHaH69K"
reputation_nft = "HsxZ1cg5H1zvvdyngaLTrB9DZ1YFrEAFMNR21fKCzioW"

[programs.testnet]
bounty_escrow = "3aiStNroDenw7KpSKXvFWVFox35gCk4FcUx8nzXRF2HH"
vulnerability_registry = "5mCoaixH9VVepuSsnhB769263Gg4RqBCEkkoJuHaH69K"
reputation_nft = "HsxZ1cg5H1zvvdyngaLTrB9DZ1YFrEAFMNR21fKCzioW"

[programs.mainnet]
bounty_escrow = "3aiStNroDenw7KpSKXvFWVFox35gCk4FcUx8nzXRF2HH"
vulnerability_registry = "5mCoaixH9VVepuSsnhB769263Gg4RqBCEkkoJuHaH69K"
reputation_nft = "HsxZ1cg5H1zvvdyngaLTrB9DZ1YFrEAFMNR21fKCzioW"

[toolchain]
anchor_version = "0.30.1"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 60000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false